//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("linqptcModel", "FK_Item_Item", "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcApplicationSales.Models.Order), "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplicationSales.Models.Item), true)]

#endregion

namespace MvcApplicationSales.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class linqptcEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new linqptcEntities object using the connection string found in the 'linqptcEntities' section of the application configuration file.
        /// </summary>
        public linqptcEntities() : base("name=linqptcEntities", "linqptcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new linqptcEntities object.
        /// </summary>
        public linqptcEntities(string connectionString) : base(connectionString, "linqptcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new linqptcEntities object.
        /// </summary>
        public linqptcEntities(EntityConnection connection) : base(connection, "linqptcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Items
        {
            get
            {
                if ((_Items == null))
                {
                    _Items = base.CreateObjectSet<Item>("Items");
                }
                return _Items;
            }
        }
        private ObjectSet<Item> _Items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Salesman> Salesmen
        {
            get
            {
                if ((_Salesmen == null))
                {
                    _Salesmen = base.CreateObjectSet<Salesman>("Salesmen");
                }
                return _Salesmen;
            }
        }
        private ObjectSet<Salesman> _Salesmen;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Salesmen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSalesmen(Salesman salesman)
        {
            base.AddObject("Salesmen", salesman);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="linqptcModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="item_id">Initial value of the item_id property.</param>
        public static Item CreateItem(global::System.Int32 item_id)
        {
            Item item = new Item();
            item.item_id = item_id;
            return item;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 item_id
        {
            get
            {
                return _item_id;
            }
            set
            {
                if (_item_id != value)
                {
                    Onitem_idChanging(value);
                    ReportPropertyChanging("item_id");
                    _item_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("item_id");
                    Onitem_idChanged();
                }
            }
        }
        private global::System.Int32 _item_id;
        partial void Onitem_idChanging(global::System.Int32 value);
        partial void Onitem_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private global::System.String _amount;
        partial void OnamountChanging(global::System.String value);
        partial void OnamountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order_id
        {
            get
            {
                return _order_id;
            }
            set
            {
                Onorder_idChanging(value);
                ReportPropertyChanging("order_id");
                _order_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_id");
                Onorder_idChanged();
            }
        }
        private Nullable<global::System.Int32> _order_id;
        partial void Onorder_idChanging(Nullable<global::System.Int32> value);
        partial void Onorder_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("linqptcModel", "FK_Item_Item", "Order")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("linqptcModel.FK_Item_Item", "Order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("linqptcModel.FK_Item_Item", "Order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("linqptcModel.FK_Item_Item", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("linqptcModel.FK_Item_Item", "Order", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="linqptcModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="order_id">Initial value of the order_id property.</param>
        public static Order CreateOrder(global::System.Int32 order_id)
        {
            Order order = new Order();
            order.order_id = order_id;
            return order;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 order_id
        {
            get
            {
                return _order_id;
            }
            set
            {
                if (_order_id != value)
                {
                    Onorder_idChanging(value);
                    ReportPropertyChanging("order_id");
                    _order_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("order_id");
                    Onorder_idChanged();
                }
            }
        }
        private global::System.Int32 _order_id;
        partial void Onorder_idChanging(global::System.Int32 value);
        partial void Onorder_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String customer_name
        {
            get
            {
                return _customer_name;
            }
            set
            {
                Oncustomer_nameChanging(value);
                ReportPropertyChanging("customer_name");
                _customer_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("customer_name");
                Oncustomer_nameChanged();
            }
        }
        private global::System.String _customer_name;
        partial void Oncustomer_nameChanging(global::System.String value);
        partial void Oncustomer_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> code
        {
            get
            {
                return _code;
            }
            set
            {
                OncodeChanging(value);
                ReportPropertyChanging("code");
                _code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("code");
                OncodeChanged();
            }
        }
        private Nullable<global::System.Int32> _code;
        partial void OncodeChanging(Nullable<global::System.Int32> value);
        partial void OncodeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("linqptcModel", "FK_Item_Item", "Item")]
        public EntityCollection<Item> Items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Item>("linqptcModel.FK_Item_Item", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Item>("linqptcModel.FK_Item_Item", "Item", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="linqptcModel", Name="Salesman")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Salesman : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Salesman object.
        /// </summary>
        /// <param name="salesman_id">Initial value of the salesman_id property.</param>
        public static Salesman CreateSalesman(global::System.Int32 salesman_id)
        {
            Salesman salesman = new Salesman();
            salesman.salesman_id = salesman_id;
            return salesman;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 salesman_id
        {
            get
            {
                return _salesman_id;
            }
            set
            {
                if (_salesman_id != value)
                {
                    Onsalesman_idChanging(value);
                    ReportPropertyChanging("salesman_id");
                    _salesman_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("salesman_id");
                    Onsalesman_idChanged();
                }
            }
        }
        private global::System.Int32 _salesman_id;
        partial void Onsalesman_idChanging(global::System.Int32 value);
        partial void Onsalesman_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String salesman_name
        {
            get
            {
                return _salesman_name;
            }
            set
            {
                Onsalesman_nameChanging(value);
                ReportPropertyChanging("salesman_name");
                _salesman_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("salesman_name");
                Onsalesman_nameChanged();
            }
        }
        private global::System.String _salesman_name;
        partial void Onsalesman_nameChanging(global::System.String value);
        partial void Onsalesman_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> code
        {
            get
            {
                return _code;
            }
            set
            {
                OncodeChanging(value);
                ReportPropertyChanging("code");
                _code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("code");
                OncodeChanged();
            }
        }
        private Nullable<global::System.Int32> _code;
        partial void OncodeChanging(Nullable<global::System.Int32> value);
        partial void OncodeChanged();

        #endregion

    
    }

    #endregion

    
}
